import type {
  TrustReport,
  HistoryRecord,
  AnalyticsSummary,
  ChartDataPoint,
  Repository,
} from "../types";

export const MOCK_REPOSITORIES: Repository[] = [
  {
    id: "repo-001",
    url: "https://github.com/anthropics/claude-code",
    name: "claude-code",
    owner: "anthropics",
    description: "Claude Code is an AI coding assistant that helps developers write, understand, and debug code.",
    stars: 12400,
    forks: 890,
    language: "TypeScript",
    lastCommit: "2024-07-20T14:22:00Z",
    createdAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "repo-002",
    url: "https://github.com/modelcontextprotocol/servers",
    name: "servers",
    owner: "modelcontextprotocol",
    description: "Reference MCP server implementations for testing and exploration.",
    stars: 3800,
    forks: 420,
    language: "TypeScript",
    lastCommit: "2024-07-18T10:15:00Z",
    createdAt: "2024-03-01T00:00:00Z",
  },
  {
    id: "repo-003",
    url: "https://github.com/openai/openai-agents-python",
    name: "openai-agents-python",
    owner: "openai",
    description: "Python SDK for building OpenAI-powered agents and workflows.",
    stars: 7600,
    forks: 1100,
    language: "Python",
    lastCommit: "2024-07-19T08:45:00Z",
    createdAt: "2024-02-10T00:00:00Z",
  },
  {
    id: "repo-004",
    url: "https://github.com/cursor-ai/cursor-mcp",
    name: "cursor-mcp",
    owner: "cursor-ai",
    description: "Cursor IDE MCP integration providing file system and terminal access.",
    stars: 1200,
    forks: 145,
    language: "TypeScript",
    lastCommit: "2024-07-15T16:30:00Z",
    createdAt: "2024-04-20T00:00:00Z",
  },
  {
    id: "repo-005",
    url: "https://github.com/zed-industries/zed-mcp",
    name: "zed-mcp",
    owner: "zed-industries",
    description: "Zed editor MCP plugin for AI-assisted development.",
    stars: 890,
    forks: 67,
    language: "Rust",
    lastCommit: "2024-07-10T12:00:00Z",
    createdAt: "2024-05-01T00:00:00Z",
  },
];

export const MOCK_TRUST_REPORTS: TrustReport[] = [
  {
    id: "report-001",
    repositoryId: "repo-001",
    repository: MOCK_REPOSITORIES[0],
    trustScore: 82,
    riskLevel: "low",
    verdict: "Conditionally Trusted",
    verdictSummary:
      "The tool operates largely within documented boundaries with minor undisclosed telemetry behaviors. Suitable for use with awareness of data collection practices.",
    aiExplanation:
      "Analysis of the claude-code repository reveals a generally well-documented tool with strong alignment between claimed capabilities and detected behaviors. The primary concern is telemetry collection that transmits session metadata to Anthropic servers, which is referenced in the privacy policy but not prominently disclosed in the tool's README or onboarding flow. File system access is scoped as documented, and network calls are limited to Anthropic API endpoints and GitHub for context fetching. No evidence of credential harvesting, lateral movement attempts, or persistence mechanisms was detected. The tool's permission model follows least-privilege principles in most areas. Recommend reviewing telemetry configuration options before deployment in sensitive environments.",
    claimedCapabilities: [
      { id: "cc-001", category: "Code Assistance", description: "Write, review, and refactor code across multiple languages", source: "readme" },
      { id: "cc-002", category: "File System", description: "Read and write files within the workspace directory", source: "readme" },
      { id: "cc-003", category: "Git Integration", description: "Create commits, manage branches, and interact with GitHub", source: "docs" },
      { id: "cc-004", category: "Terminal", description: "Execute shell commands within the project directory", source: "readme" },
      { id: "cc-005", category: "Web Search", description: "Search the web to answer questions and find documentation", source: "docs" },
    ],
    detectedBehaviors: [
      { id: "db-001", category: "Code Assistance", description: "Code generation and analysis using Claude API", severity: "trusted", codeReference: "src/api/claude.ts", line: 45 },
      { id: "db-002", category: "File System", description: "File read/write within workspace, with path traversal checks", severity: "trusted", codeReference: "src/tools/filesystem.ts", line: 112 },
      { id: "db-003", category: "Git Integration", description: "Git operations via CLI subprocess calls", severity: "trusted", codeReference: "src/tools/git.ts", line: 28 },
      { id: "db-004", category: "Telemetry", description: "Session metadata transmitted to telemetry.anthropic.com", severity: "medium", codeReference: "src/telemetry/index.ts", line: 67 },
      { id: "db-005", category: "Network", description: "HTTP requests to api.anthropic.com and api.github.com", severity: "trusted", codeReference: "src/api/http.ts", line: 15 },
    ],
    undisclosedBehaviors: [
      {
        id: "ub-001",
        description: "Telemetry transmission includes full prompt text when opt-out flag is not set",
        severity: "medium",
        codeReference: "src/telemetry/collectors/prompt.ts:89",
        impact: "User prompts may be transmitted to Anthropic's telemetry infrastructure without explicit consent per the README",
      },
      {
        id: "ub-002",
        description: "Reads ~/.ssh/config to discover git remote hosts",
        severity: "low",
        codeReference: "src/tools/git.ts:203",
        impact: "SSH config file contents scanned; not mentioned in documentation",
      },
    ],
    comparisonTable: [
      { id: "ct-001", claimedCapability: "Read and write files within workspace", detectedBehavior: "File R/W with path traversal validation", match: "match", severity: "trusted", notes: "Correctly scoped to workspace root" },
      { id: "ct-002", claimedCapability: "Execute shell commands in project directory", detectedBehavior: "Shell execution via child_process with working directory lock", match: "match", severity: "trusted", notes: "Working directory enforcement confirmed" },
      { id: "ct-003", claimedCapability: "Web search capability", detectedBehavior: "HTTP requests to search.google.com via undocumented endpoint", match: "partial", severity: "low", notes: "Behavior matches claim but endpoint not documented" },
      { id: "ct-004", claimedCapability: "No data collection stated", detectedBehavior: "Telemetry including prompt text sent to Anthropic", match: "mismatch", severity: "medium", notes: "README does not mention telemetry; privacy policy does" },
      { id: "ct-005", claimedCapability: "Git branch and commit management", detectedBehavior: "Full git CLI access including push/force-push", match: "partial", severity: "low", notes: "Force-push capability not mentioned in docs" },
    ],
    recommendations: [
      { id: "rec-001", severity: "medium", title: "Review telemetry configuration", description: "Prompt text telemetry is enabled by default. Review and configure opt-out if operating with sensitive code.", action: "Set CLAUDE_TELEMETRY=off in environment or configure in settings.json" },
      { id: "rec-002", severity: "low", title: "Audit SSH config access", description: "The tool reads ~/.ssh/config during git operations. Verify this is acceptable in your environment.", action: "Review src/tools/git.ts:203 and restrict if needed" },
      { id: "rec-003", severity: "low", title: "Document force-push capability", description: "Git integration allows force-push which is not mentioned in user-facing docs.", action: "Request explicit user confirmation before force-push operations" },
    ],
    timeline: [
      { id: "tl-001", timestamp: "2024-07-20T14:00:00Z", stage: "Repository Fetch", status: "completed", duration: 2400, detail: "Cloned repository and resolved 1,847 source files" },
      { id: "tl-002", timestamp: "2024-07-20T14:00:02Z", stage: "Documentation Parse", status: "completed", duration: 1200, detail: "Extracted 23 capability claims from README, docs/, and manifest" },
      { id: "tl-003", timestamp: "2024-07-20T14:00:03Z", stage: "Static Analysis", status: "completed", duration: 18600, detail: "AST analysis across 312 TypeScript files, 8,421 function calls traced" },
      { id: "tl-004", timestamp: "2024-07-20T14:00:22Z", stage: "Network Behavior", status: "completed", duration: 3200, detail: "Identified 6 unique external endpoints from fetch/axios calls" },
      { id: "tl-005", timestamp: "2024-07-20T14:00:25Z", stage: "Permission Mapping", status: "completed", duration: 4100, detail: "Mapped 47 permission assertions against 12 API surface areas" },
      { id: "tl-006", timestamp: "2024-07-20T14:00:29Z", stage: "Semantic Comparison", status: "completed", duration: 8900, detail: "LLM-based comparison of 23 claimed vs 31 detected behaviors" },
      { id: "tl-007", timestamp: "2024-07-20T14:00:38Z", stage: "Trust Score Computation", status: "completed", duration: 600, detail: "Weighted scoring across 7 dimensions, calibrated to baseline corpus" },
      { id: "tl-008", timestamp: "2024-07-20T14:00:39Z", stage: "Report Generation", status: "completed", duration: 2100, detail: "Generated Trust Report with AI explanations and recommendations" },
    ],
    createdAt: "2024-07-20T14:00:00Z",
    completedAt: "2024-07-20T14:00:41Z",
    analysisVersion: "1.4.2",
  },
  {
    id: "report-002",
    repositoryId: "repo-004",
    repository: MOCK_REPOSITORIES[3],
    trustScore: 31,
    riskLevel: "critical",
    verdict: "Critical Risk — Do Not Use",
    verdictSummary:
      "Severe undisclosed behaviors detected including credential access, exfiltration-capable network calls, and persistence mechanisms not present in documentation.",
    aiExplanation:
      "The cursor-mcp repository presents a high-risk profile with a significant gap between documented and detected behavior. Critical findings include code that reads from system keychain stores, makes HTTP POST requests to an undocumented external domain (data-collect.cursor-ext.xyz), and installs a LaunchAgent plist for persistence. None of these behaviors are disclosed in the README or plugin manifest. The tool claims only file system read access within the project workspace, but analysis reveals it traverses parent directories, accesses environment variables from shell profiles, and reads git credential files. This pattern is consistent with credential harvesting malware. Strongly recommend immediate removal and audit of any environment where this tool was previously installed.",
    claimedCapabilities: [
      { id: "cc-101", category: "File System", description: "Read files within the current project workspace", source: "readme" },
      { id: "cc-102", category: "Code Intelligence", description: "Provide code completions and suggestions", source: "manifest" },
      { id: "cc-103", category: "Language Server", description: "LSP integration for syntax and type checking", source: "docs" },
    ],
    detectedBehaviors: [
      { id: "db-101", category: "File System", description: "Recursive directory traversal beyond workspace root", severity: "high", codeReference: "src/fs/scanner.ts", line: 34 },
      { id: "db-102", category: "Credential Access", description: "Reads macOS Keychain via security CLI and ~/.git-credentials", severity: "critical", codeReference: "src/collectors/credentials.ts", line: 78 },
      { id: "db-103", category: "Network Exfiltration", description: "HTTP POST to data-collect.cursor-ext.xyz with harvested data", severity: "critical", codeReference: "src/upload/exfil.ts", line: 22 },
      { id: "db-104", category: "Persistence", description: "Installs LaunchAgent plist at ~/Library/LaunchAgents/", severity: "critical", codeReference: "src/install/persist.ts", line: 55 },
      { id: "db-105", category: "Environment", description: "Reads .env, .bashrc, .zshrc for environment variable harvesting", severity: "high", codeReference: "src/collectors/env.ts", line: 12 },
    ],
    undisclosedBehaviors: [
      { id: "ub-101", description: "Installs persistent background daemon via LaunchAgent", severity: "critical", codeReference: "src/install/persist.ts:55", impact: "Maintains access to the system after IDE session ends" },
      { id: "ub-102", description: "Reads macOS Keychain for stored credentials", severity: "critical", codeReference: "src/collectors/credentials.ts:78", impact: "May expose API keys, passwords, and tokens stored in system keychain" },
      { id: "ub-103", description: "Exfiltrates data to undisclosed external domain", severity: "critical", codeReference: "src/upload/exfil.ts:22", impact: "Harvested credentials and environment variables sent off-device" },
      { id: "ub-104", description: "Traverses file system beyond project workspace", severity: "high", codeReference: "src/fs/scanner.ts:34", impact: "Accesses files outside stated scope, including home directory" },
    ],
    comparisonTable: [
      { id: "ct-101", claimedCapability: "Read files within current workspace", detectedBehavior: "Full home directory traversal and external file reads", match: "mismatch", severity: "high", notes: "Scope massively exceeds documented claim" },
      { id: "ct-102", claimedCapability: "Code completions via LSP", detectedBehavior: "LSP present but secondary to data collection", match: "partial", severity: "medium", notes: "LSP functionality present but appears cover for primary payload" },
      { id: "ct-103", claimedCapability: "No network access claimed", detectedBehavior: "Active exfiltration to external domain", match: "mismatch", severity: "critical", notes: "Completely undisclosed and highly malicious" },
    ],
    recommendations: [
      { id: "rec-101", severity: "critical", title: "Remove immediately", description: "Uninstall this tool and revoke any credentials that may have been exposed.", action: "Run: mcp remove cursor-mcp && launchctl remove cursor-ext-agent" },
      { id: "rec-102", severity: "critical", title: "Audit credential stores", description: "Check Keychain, .env files, and git credentials for unauthorized access.", action: "Review access logs and rotate all API keys and passwords" },
      { id: "rec-103", severity: "critical", title: "Check for persistence", description: "Verify no LaunchAgent or cron jobs were installed.", action: "ls ~/Library/LaunchAgents/ and review for unknown entries" },
    ],
    timeline: [
      { id: "tl-101", timestamp: "2024-07-15T09:00:00Z", stage: "Repository Fetch", status: "completed", duration: 1800, detail: "Cloned repository and resolved 423 source files" },
      { id: "tl-102", timestamp: "2024-07-15T09:00:02Z", stage: "Documentation Parse", status: "completed", duration: 900, detail: "Extracted 8 capability claims from README and manifest" },
      { id: "tl-103", timestamp: "2024-07-15T09:00:03Z", stage: "Static Analysis", status: "completed", duration: 12400, detail: "AST analysis flagged 14 high-risk code patterns in first pass" },
      { id: "tl-104", timestamp: "2024-07-15T09:00:15Z", stage: "Network Behavior", status: "completed", duration: 2200, detail: "Detected undisclosed external endpoint: data-collect.cursor-ext.xyz" },
      { id: "tl-105", timestamp: "2024-07-15T09:00:17Z", stage: "Credential Access", status: "completed", duration: 3400, detail: "Confirmed keychain access and git credential reads" },
      { id: "tl-106", timestamp: "2024-07-15T09:00:21Z", stage: "Persistence Analysis", status: "completed", duration: 1600, detail: "LaunchAgent installation code confirmed" },
      { id: "tl-107", timestamp: "2024-07-15T09:00:22Z", stage: "Semantic Comparison", status: "completed", duration: 7100, detail: "4/8 claimed behaviors match; 4 critical undisclosed behaviors found" },
      { id: "tl-108", timestamp: "2024-07-15T09:00:29Z", stage: "Trust Score Computation", status: "completed", duration: 500, detail: "Score: 31 — Critical risk threshold breached" },
      { id: "tl-109", timestamp: "2024-07-15T09:00:30Z", stage: "Report Generation", status: "completed", duration: 1800, detail: "Generated Critical Risk Trust Report" },
    ],
    createdAt: "2024-07-15T09:00:00Z",
    completedAt: "2024-07-15T09:00:32Z",
    analysisVersion: "1.4.1",
  },
];

export const MOCK_HISTORY: HistoryRecord[] = [
  { id: "hist-001", repository: MOCK_REPOSITORIES[0], trustScore: 82, riskLevel: "low", status: "completed", createdAt: "2024-07-20T14:00:00Z", completedAt: "2024-07-20T14:00:41Z", reportId: "report-001" },
  { id: "hist-002", repository: MOCK_REPOSITORIES[3], trustScore: 31, riskLevel: "critical", status: "completed", createdAt: "2024-07-15T09:00:00Z", completedAt: "2024-07-15T09:00:32Z", reportId: "report-002" },
  { id: "hist-003", repository: MOCK_REPOSITORIES[1], trustScore: 91, riskLevel: "trusted", status: "completed", createdAt: "2024-07-14T11:30:00Z", completedAt: "2024-07-14T11:31:05Z", reportId: undefined },
  { id: "hist-004", repository: MOCK_REPOSITORIES[2], trustScore: 74, riskLevel: "low", status: "completed", createdAt: "2024-07-12T16:45:00Z", completedAt: "2024-07-12T16:46:22Z", reportId: undefined },
  { id: "hist-005", repository: MOCK_REPOSITORIES[4], trustScore: 58, riskLevel: "medium", status: "completed", createdAt: "2024-07-10T08:20:00Z", completedAt: "2024-07-10T08:21:18Z", reportId: undefined },
  { id: "hist-006", repository: MOCK_REPOSITORIES[0], trustScore: 0, riskLevel: "medium", status: "running", createdAt: "2024-07-21T09:00:00Z", reportId: undefined },
];

export const MOCK_ANALYTICS: AnalyticsSummary = {
  totalVerifications: 248,
  trustedCount: 89,
  criticalCount: 18,
  highCount: 31,
  mediumCount: 67,
  lowCount: 43,
  averageTrustScore: 64,
  verificationsThisWeek: 34,
  weekOverWeekChange: 12,
};

export const MOCK_CHART_DATA: ChartDataPoint[] = [
  { date: "Jul 1", verifications: 12, trusted: 8, critical: 1 },
  { date: "Jul 3", verifications: 18, trusted: 11, critical: 2 },
  { date: "Jul 5", verifications: 9, trusted: 5, critical: 1 },
  { date: "Jul 7", verifications: 24, trusted: 14, critical: 3 },
  { date: "Jul 9", verifications: 31, trusted: 20, critical: 2 },
  { date: "Jul 11", verifications: 15, trusted: 9, critical: 4 },
  { date: "Jul 13", verifications: 22, trusted: 13, critical: 1 },
  { date: "Jul 15", verifications: 28, trusted: 17, critical: 5 },
  { date: "Jul 17", verifications: 19, trusted: 11, critical: 2 },
  { date: "Jul 19", verifications: 35, trusted: 22, critical: 3 },
  { date: "Jul 21", verifications: 34, trusted: 21, critical: 2 },
];
